### ISSUE TITLE
Daylight calendar now displaying 3-6 events per day 

### ISSUE THREAD

**Issue by elinaru** [chrisblakley/Daylight-Calendar-ICS#18] opened 2024-08-06 21:23 UTC
Starting today, the calendar has three to six events per day in the calendar. Each event appears to be a near duplicate. 

For instance, today's (Aug 6, 2024) event "13h 57m (58.1%) [83.2 Percentile]."  is duplicated six times with the only difference being this line in the description text: 

[Last Updated: Monday, August 5, 2024, 4:01pm] 
[Last Updated: Monday, August 5, 2024, 10:01pm] 
[Last Updated: Tuesday, August 6, 2024, 12:01pm] 
[Last Updated: Tuesday, August 6, 2024, 5:01am] 
[Last Updated: Tuesday, August 6, 2024, 1:01pm] 
[Last Updated: Monday, August 5, 2024, 11:01pm] 

Can anything be done to one again display only one event per day?  
Thanks! 
Elina

**Comment by chrisblakley** [comment] 2024-08-06 21:26
I noticed this as well today. I have another calendar that syncs from a different endpoint and it is also duplicated.

I think this may be a temporary issue with Google Calendar because there have been no changes to the code between yesterday and today when it began happening.

For now, I'd recommend hiding the calendar and let's monitor the issue to see if it gets resolved on their end. I am not sure what I'd be able to do in the code as there are no duplicates locally.

Thanks for confirming the issue is happening to others, too!

**Comment by elinaru** [comment] 2024-08-07 18:07
Hi Chris,

Thanks for the quick response! Hopefully an update on Google side solves
the issue.

Thanks again,
Elina

**Comment by crpAnderson** [comment] 2024-08-07 20:50
I'm also seeing this behavior

**Comment by chrisblakley** [comment] 2024-08-07 20:55
Can anyone confirm if this is happening to other subscribed calendars via URL as well or just this one?

**Comment by crpAnderson** [comment] 2024-08-07 21:02
I am using a subscribed calendar but I see the same behavior in the standalone URL
http://gearside.com/calendars/daylight.php?lat=44.8&lng=-93.14&gmt=-6
![image](https://github.com/user-attachments/assets/226cadaf-d5c0-42c2-ae61-102bb8c66b0a)

**Comment by chrisblakley** [comment] 2024-08-07 21:10
Thanks– I'm curious if other different calendars that are subscribed in the same was as this Daylight calendar are showing the same problems. I have another completely different calendar that Google Calendar is duplicating too, but it is also from the same domain so I don't know if that indicates a global problem or something local to this server.

If I delete and re-add the Daylight calendar, it goes back to just a single event for each day, so the duplication problem does not appear to be with the ICS file that it generates– it implies that Google Calendar isn't swapping the old for the new properly. I'll see if this re-adding of the calendar starts duplicating again or not.

Hopefully we can get this figured out soon!

**Comment by crpAnderson** [comment] 2024-08-07 22:35
When I remove the calendar and re-subscribe I still get the duplication problem.

**Comment by coman49** [comment] 2024-08-08 02:30
Same issue here, noticed it a few days ago for me. I have other calendars I'm subscribed to in the same way (via URL) and they don't have this issue. If I remove the calendar and then re-add it with something like &nocache at the end of the URL then duplicates disappear at first but sometime later they reappear again. Also tried turning offline off but didn't help. Duplication is not consistent, for example right now some days show normal single entry, some days show 2 duplicate entries, some show 3 identical entries. And as somebody else mentioned, the only difference between the entries is this line - "[Last Updated: Wednesday, August 7, 2024, 11:40am] ".

**Comment by chrisblakley** [comment] 2024-08-08 02:34
Thanks for the additional info. I'll continue to look into it!

**Comment by chrisblakley** [comment] 2024-08-08 03:11
I made an adjustment to the "UID" value of each event to try to be unique and consistent between when Google Calendar retrieves new data.

I'll be testing this by re-adding the calendar (with a query string to bust the cache) and waiting for Google to update it over the course of a day or two. Anyone else is welcome to give it a try as well. `https://gearside.com/calendars/daylight.php?asdfasdf`

If this doesn't work I'll continue reviewing it!

**Comment by chrisblakley** [comment] 2024-08-08 22:02
This latest update seems promising so far– Google has updated the calendar a few times and have seen no duplicates.

Unfortunately, it does not appear that the old calendar is automatically removing duplicates, so the solution may require us to re-add the calendar to resolve this.

Will keep an eye on it still.

**Comment by bobk26** [comment] 2024-08-09 16:34
> This latest update seems promising so far– Google has updated the calendar a few times and have seen no duplicates.
> 
> Unfortunately, it does not appear that the old calendar is automatically removing duplicates, so the solution may require us to re-add the calendar to resolve this.
> 
> Will keep an eye on it still.

I'm encountering this duplication issue, and I just tried removing and re-adding the calendar, and it had no effect. Perhaps the Google fix hasn't been pushed live yet?

**Comment by chrisblakley** [comment] 2024-08-09 16:59
Google Calendar does cache the URLs, so if you used the same URL as previous it might not actually retrieve the new code (if you're using the gearside.com endpoint). Try adding a random query string to the end like `?asdfwer3751` if you haven't already (and make sure the new random query string is different than one you've previously used).

Once we determine that new code is working then I'll push the commit to GitHub here.

**Comment by coman49** [comment] 2024-08-09 16:59
It's working for me so far, no duplicates, it's been about half a day. Make sure to add "&nocache" at the end of the URL when re-adding it back.

**Comment by bobk26** [comment] 2024-08-09 19:10
> It's working for me so far, no duplicates, it's been about half a day. Make sure to add "&nocache" at the end of the URL when re-adding it back.

The nocache fixed it, thank you!

Do I need to keep nocache in the url forever? I don't want to use resources unnecessarily. Thanks!

**Comment by chrisblakley** [comment] 2024-08-09 19:19
I would leave it on for as long as you want to use this calendar– and if in the future anything else comes up where we need to publish new code you can update the nocache query string again to get fresh data.

It does not use any additional resources, so nothing to worry about there!

Glad to hear this worked! For anyone subscribing to the gearside.com endpoint, it looks like this fix is good so feel free to update your calendar URLs. Anyone using the PHP code itself, I will push a commit to this repo sometime this weekend!

**Comment by chrisblakley** [comment] 2024-08-10 15:17
Closing as this fix has been committed. If for some reason it still occurs feel free to continue the discussion here or we can re-open if needed. Any issues that are similar but not directly related to duplicate events feel free to create a new issue. Thanks everyone!

**Closed** 2024-08-10 15:16 UTC
Labels: bug
